version: "3.9"

services:
  app:
    container_name: app
    build: .
    depends_on:
      - mongo
      - postgres
    ports:
      - "3000:3000"
    env_file: ".env"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - MAILER_ACCOUNT=${MAILER_ACCOUNT}
      - MAILER_PASS=${MAILER_PASS}
      - HOST=postgres_db
      - DB_DIALECT=${DB_DIALECT}
    networks:
      - node-app

  mongo:
    container_name: mongo
    image: mongo:4.4.7-focal
    restart: always
    ports:
      - "27017:27017"
    networks:
      - node-app

  postgres:
    container_name: postgres_db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456789
    networks:
      - node-app

networks:
  node-app:
    driver: bridge
